tc_site/web_application/main_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from main_system import (
    views,
    startup,
    decorators,
)
from . import settings
import django.views.static

handler404 = 'tc_web.views.err404'
handler500 = 'tc_web.views.err500'

urlpatterns = [
    url(r'^accounts/login/$',
        decorators.startup_page_init('search')(auth_views.login),
        name='login'),
    url(r'^accounts/logout/$',
        auth_views.logout,
        {'next_page': '/'},
        name='logout'),
    url(r'^accounts/signup/$', views.signup, name='signup'),

    path('tc_web/', include('tc_web.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
]

if not settings.DEBUG:
    urlpatterns.append(path('static/<path>.', django.views.static.serve,
                            {'document_root': settings.STATIC_ROOT}))


startup.start_up()

tc_site/web_application/tc_web/urls.py
from django.urls import path
from django.conf.urls import url
from tc_web import views
from tc_web.tasks import views as task_views
from tc_web.projects import views as project_views


app_name = 'tc_web'


urlpatterns = [
    path('', views.index, name='index'),

    path('tasks/', task_views.tasks, name='tasks'),
    path('projects/', project_views.projects, name='projects'),

    path('tasks/add_task/', task_views.add_task, name='add_task'),
    path('tasks/<int:project_id>/add_task/',
         task_views.add_task,
         name='add_project_task'),
    path('tasks/<int:project_id>/add_task/<int:task_id>/',
         task_views.add_task,
         name='add_child_project_task'),
    path('tasks/add_task/<int:task_id>/',
         task_views.add_task,
         name='add_child_task'),
    path('tasks/change_task/<int:task_id>/',
         task_views.change_task,
         name='change_task'),
    path('tasks/show_task/<int:task_id>/',
         task_views.show_task,
         name='show_task'),

    path('projects/add_project/',
         project_views.add_project,
         name='add_project'),

    path('project/<int:project_id>/', task_views.project, name='project'),
    path('project/<int:project_id>/add_user',
         project_views.add_user,
         name='add_user'),
    path('projects/change_project/<int:project_id>/',
         project_views.change_project,
         name='change_project'),

    path('profile/id<int:user_id>/', views.profile, name='profile'),
    path('profile/change_profile/<int:user_id>/',
         views.change_profile,
         name='change_profile'),

    url(r'^api/get_users/', views.get_users, name='get_users'),
    path('api/get_project_users/<int:project_id>/',
         views.get_project_users,
         name='get_project_users')
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

tc_site/web_application/tc_web/models.py
from peewee import *

tc_site/web_application/tc_web/forms.py
from django import forms
from time_candle.enums.status import status_dict, Status
from time_candle.enums.priority import priority_dict, Priority


class ChangeProfileForm(forms.Form):
    nickname = forms.CharField(max_length=30,
                               required=True)
    about = forms.CharField(max_length=550, required=False)

tc_site/web_application/tc_web/projects/forms.py
from django import forms


class ProjectForm(forms.Form):
    title = forms.CharField(
        label='project\'s title', max_length=30, required=True)
    description = forms.CharField(label='description', required=False,
                                  widget=forms.Textarea)

tc_site/web_application/tc_web/tasks/forms.py
from django import forms
from time_candle.enums.status import status_dict, Status
from time_candle.enums.priority import priority_dict, Priority
from tempus_dominus.widgets import DateTimePicker


STATUS_CHOICES = tuple(status_dict.items())
PRIORITY_CHOICES = tuple(priority_dict.items())


class AddTask(forms.Form):
    title = forms.CharField(label='task\'s title', max_length=60, required=True)
    comment = forms.CharField(label='comment', max_length=155, required=False)
    deadline_time = forms.CharField(label='deadline', required=False,
                                    help_text='Format: YYYY-MM-DD hh:mm:ss',
                                    widget=DateTimePicker())
    priority = forms.ChoiceField(
        label='priority', choices=PRIORITY_CHOICES, initial=Priority.MEDIUM,
        required=False, widget=forms.Select())
    status = forms.ChoiceField(
        label='status', choices=STATUS_CHOICES, initial=Status.IN_PROGRESS,
        required=False)
    period = forms.FloatField(label='period in days', required=False)


class ChangeTask(forms.Form):
    comment = forms.CharField(label='comment', max_length=155, required=False)
    deadline_time = forms.CharField(label='deadline', required=False,
                                    help_text='Format: YYYY-MM-DD hh:mm:ss',
                                    widget=DateTimePicker())
    priority = forms.ChoiceField(label='priority', choices=PRIORITY_CHOICES,
                                 required=False, widget=forms.Select())
    status = forms.ChoiceField(
        label='status', choices=STATUS_CHOICES, required=False)

tc_site/web_application/tc_web/projects/views.py
from django.http import Http404
from django.shortcuts import (
    render,
    redirect,
)
from django.urls import reverse
from django.contrib.auth.models import User
from time_candle.exceptions import AppException
from tc_web.projects import (
    forms,
    shortcuts,
)
from main_system import decorators
from main_system import shortcuts as base_shortcuts
from tc_web import logger
from django.contrib.auth.decorators import login_required


@login_required
@decorators.startup_page_init('search')
def projects(request):
    controller = base_shortcuts.get_controller(request)
    projects_list = controller.get_projects('')

    context = {
        'projects_list': projects_list
    }

    try:
        redirect_view = shortcuts.project_card_post_form(request, controller)

        # if we can redirect, then do it, else just render or render with errors
        # our template
        if redirect_view:
            logger.debug('redirect due to changes...')
            return redirect_view

        # adding some fields for better view
        shortcuts.init_projects(request, controller, projects_list)

    except AppException as e:
        context['errors'] = e.errors.value
        logger.warning(e.errors.value)

        # the errors doesn't
        shortcuts.init_projects(request, controller, projects_list)

    logger.debug('all projects rendered')
    return render(request, 'tc_web/projects/projects.html', context)


@login_required
@decorators.startup_page_init('search')
def add_project(request):
    if request.method == 'POST':
        form = forms.ProjectForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')

            controller = base_shortcuts.get_controller(request)

            controller.add_project(title=title,
                                   description=description,
                                   members=[])
            logger.debug('project added')

            return redirect(reverse('tc_web:projects'))

    else:
        form = forms.ProjectForm()

    return render(request, 'tc_web/projects/add_project.html', {'form': form})


@login_required
@decorators.startup_page_init('search')
def change_project(request, project_id):
    context = {'errors': None}
    controller = base_shortcuts.get_controller(request)

    if request.method == 'POST':
        form = forms.ProjectForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')

            # if description if empty we pass it as not-to-change param
            if not description:
                description = None

            try:
                controller.change_project(project_id, title, description)
                logger.debug('project changed')

                return redirect(reverse('tc_web:projects'))
            except AppException as e:
                logger.debug(e.errors.value)
                context['errors'] = e.errors.value

    else:
        form = forms.ProjectForm()

    context['form'] = form

    # try because we can have some problems with rights when we try to visit
    # page
    try:
        project = controller.get_project(project_id)
        context['project'] = project
        form.fields['title'].widget.attrs.update({'value': project.title})
        form.fields['description'].widget.attrs.update(
            {'placeholder': project.description})

    except AppException as e:
        logger.warning(e.errors.value)
        raise Http404

    # if you are not admin and there was no errors for you before
    if request.user.id != project.admin_uid and not context['errors']:
        logger.debug('dont have rights for changing the project')
        context['errors'] = 'You know that you cannot do that, right?'

    return render(request, 'tc_web/projects/change_project.html', context)


@login_required
@decorators.startup_page_init('search')
def add_user(request, project_id):
    context = {}
    controller = base_shortcuts.get_controller(request)

    if request.method == 'POST':

        # trying to add user to project
        try:
            # searching selected user in database
            try:
                if 'search_user' in request.POST \
                        and request.POST['search_user']:
                    user_id = User.objects.get(
                        username=request.POST['search_user']).id
                else:
                    user_id = None

            except User.DoesNotExist:
                # we need this for more elegant way to catch exception
                errors = type('dummy', (), {})()
                errors.value = 'User does not exists'
                logger.warning(errors.value)
                raise AppException(errors)

            controller.add_user_to_project(user_id, project_id)
            logger.debug('user to project was added')

            return redirect(reverse('tc_web:project', args=(project_id,)))

        except AppException as e:
            context['errors'] = e.errors.value

    # try because we can have some problems with rights when we try to visit
    # page
    try:
        project = controller.get_project(project_id)

    except AppException as e:
        logger.warning(e.errors.value)
        raise Http404

    # if you are not admin and there was no errors for you before
    if request.user.id != project.admin_uid and not context['errors']:
        context['errors'] = 'You know that you cannot do that, right?'

    return render(request, 'tc_web/projects/add_user.html', context)

tc_site/web_application/tc_web/views.py
from django.http import (
    HttpResponse,
    Http404,
)
from django.shortcuts import render, redirect
from django.urls import reverse
from time_candle.exceptions import AppException
from tc_web import (
    forms,
    logger,
)
from main_system import (
    shortcuts,
    decorators,
)
from django.contrib.auth.models import User
import json
from django.contrib.auth.decorators import login_required


def err404(request, exception):
    logger.debug('Http404 error raised')
    return render(
        request, 'tc_web/404.html', status=404)


def err500(request, exception):
    logger.debug('Http500 error raised')
    return render(
        request, 'tc_web/500.html', status=500)


@decorators.startup_page_init('search')
def index(request):
    return render(request, 'tc_web/index.html')


@decorators.startup_page_init('search')
def profile(request, user_id):
    controller = shortcuts.get_controller(request)
    context = {}

    try:
        django_user = User.objects.get(id=user_id)
        lib_user = controller.get_user(user_id)
    except (User.DoesNotExist, AppException):
        raise Http404

    # merge two user objects to get one full user info
    screen_user = shortcuts.merge_instances(django_user, lib_user)
    context['screen_user'] = screen_user

    if user_id == request.user.id:
        logger.debug('rendering delete button')

        if request.method == 'POST':
            logger.debug(request.POST)
            if 'delete' in request.POST:
                controller.remove_message(request.POST['delete'])
                return redirect(request.META.get('HTTP_REFERER'))

        logger.debug('getting our messages')
        messages = controller.get_messages()
        context['messages'] = messages

    return render(request, 'tc_web/profile.html', context)


# function for autocomplete user search
def get_users(request):
    logger.debug('ajax request to get all users has been sent')

    if request.is_ajax():
        q = request.GET.get('term', '')
        re = '^' + q + '+'
        users = User.objects.filter(username__regex=re)
        results = []
        for user in users:
            user_json = {}
            user_json['id'] = user.id
            user_json['label'] = user.username
            user_json['value'] = user.username
            results.append(user_json)
        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    logger.debug('ajax request was accepted')
    return HttpResponse(data, mimetype)


# function for autocomplete project user search
def get_project_users(request, project_id):
    logger.debug('ajax request to get project users has been sent')
    controller = shortcuts.get_controller(request)
    logger.debug('users were taken from controller')

    if request.is_ajax():
        q = request.GET.get('term', '')
        users = controller.get_users(project_id)
        users = [user for user in users if user.login.startswith(q)]
        results = []
        for user in users:
            user_json = {}
            user_json['id'] = user.uid
            user_json['label'] = user.login
            user_json['value'] = user.login
            results.append(user_json)
        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    logger.debug('ajax request was accepted')
    return HttpResponse(data, mimetype)


@login_required
@decorators.startup_page_init('search')
def change_profile(request, user_id):
    context = {}
    controller = shortcuts.get_controller(request)

    if request.method == 'POST':
        form = forms.ChangeProfileForm(request.POST)
        if form.is_valid():
            about = form.cleaned_data.get('about')
            nickname = form.cleaned_data.get('nickname')
            try:
                controller.change_user(user_id, nickname, about)
                logger.debug('user was changed')
                return redirect(reverse('tc_web:profile', args=(user_id,)))

            except AppException as e:
                context['errors'] = e.errors.value

    else:
        form = forms.ChangeProfileForm()
        user = controller.get_user(user_id)

        # init fields with default values
        form.fields['nickname'].widget.attrs.update({'value': user.nickname})
        form.fields['about'].widget.attrs.update({'value': user.about})

    context['form'] = form

    return render(request, 'tc_web/change_profile.html', context)

tc_site/web_application/tc_web/templates/tc_web/tasks/project.html
{% extends 'base.html' %}
{% block content %}
{% if project %}
<div class="row">
    <div class="col-md-12 mb-2">
         <div class="card">
         <!--Card content-->
         <div class="card-body">
              <div class="row">
                  <div class="col-sm-8">
                      <p class="h4 card-title mb-4 ml-4">{{ project.title }} <span class="grey-text">id{{ project.pid}}</span></p>
                  </div>

                  <div class="col-sm-4">
                      <h4 class="card-title text-center">Admin: <a href="{% url 'tc_web:profile' project.admin_uid %}" class="grey-text"> {{ project.admin_name }}</a><span class="grey-text">; id {{ project.pid }}</span></h4>
                  </div>
              </div>
              <p class="card-text mb-2 ml-4">{{ project.description|default:"No comments provided" }}</p>
              <hr>
              {% if project.admin_uid == user.id %}
                   <a class="btn btn-unique" href="{% url 'tc_web:change_project' project.pid %}">Change</a>
              {% endif %}
         </div>
         </div>
    </div>
 </div>
{% endif %}
{% if tasks_list %}
<div class="row">
    {% for task in tasks_list %}
        {% include 'tc_web/tasks/task_card.html' with task=task %}
    {% endfor %}
</div>
</ul>
{% else %}
<div class="card">
    {% if project %}
    <!--Card content-->
    <div class="card-body">
        <h4 class="card-title text-center">No tasks available</h4>
    </div>
    {% endif %}
</div>
{% endif %}
<!--Grid column-->
{% endblock %}

{% block add_buttons %}
{% if project %}
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-lg red" href="{% url 'tc_web:add_project_task' project.pid %}">
        <i class="fa fa-plus"></i>
    </a>
</div>
{% if project.admin_uid == user.id %}
<div class="fixed-action-btn" style="bottom: 45px; right: 100px;">
    <a class="btn-floating btn-lg red" href="{% url 'tc_web:add_user' project.pid %}">
        <i class="fa fa-user"></i>
    </a>
</div>
{% endif %}
{% endif %}

{% block sidebar %}
<!-- Sidebar -->
<div class="side-nav fixed grey lighten-5 mdb-sidenav" style="width: 18%; overflow-y: auto;">
    <ul class="custom-scrollbar list-unstyled" style="margin-top: 30%">
        <li>
        {% for user in users_list %}
        <a href="{% url 'tc_web:profile' user.uid %}" class="list-group-item list-group-item-action waves-effect">
            <i class="fa fa-user mr-3"></i>{{ user.login }}@{{ user.uid }}</a>
        {% endfor %}
        </li>
    </ul>

</div>
<!-- Sidebar -->
{% endblock %}

{% endblock %}

{% block errors %}
    {% include 'tc_web/error.html' with errors=errors %}
{% endblock %}

{% block navbar %}
    {% include 'tc_web/tasks/query_bar.html' %}
{% endblock %}

{% block scripts %}
<script>
$(function() {
    $("#search_user").autocomplete({
        source: "/tc_web/api/get_project_users/{{ project.pid }}/",
        minLength: 2,
    });
});

</script>
{% endblock %}

{% block special %}
{% endblock %}

tc_site/web_application/tc_web/templates/tc_web/tasks/query_bar.html
<form class="form-inline" method="get">
    <input class="grey lighten-5 form-control mr-sm-2" type="text" name="show_me" placeholder="Type query" aria-label="Query">
</form>

tc_site/web_application/tc_web/templates/tc_web/tasks/task_card.html
    <!--Grid column-->
    <div class="col-lg-4 col-md-6 col-sm-12 mb-4">

        <!--Card-->
        <div class="card">
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <div class="row" style="margin-bottom: -20px">
                    <div class="col-sm-9">
                        <p class="card-title h4">{{ task.title|truncatechars:18 }}
                        </p>
                    </div>

                    <div class="col-sm-3">
                        {% if task.has_rights %}
                            <form id="del_{{ task.tid }}" method="post">
                            {% csrf_token %}
                                <button value={{ task.tid }} name='delete' onclick="return clicked(event, 'del_{{ task.tid }}')"
                                     class="btn btn-red btn-sm" style="margin-top: -3px"><i class="fa fa-times"></i></button>
                            </form>
                        {% else %}
                            <a disabled="disabled" class="btn btn-grey btn-sm" style="margin-top: -3px"><i
                                class="fa fa-times"></i></a>
                        {% endif %}
                    </div>
                </div>
                <hr>
                <!--Text-->
                <div class="row">
                    <div class="col-sm-9">
                        <p class="card-text">{{ task.comment|default:"No comments provided"|truncatechars:26 }}</p>
                    </div>

                    {% if task.status == 3 %}
                    {% elif task.has_rights %}
                        <div class="col-sm-3">
                            <form method="post" id="check">
                                {% csrf_token %}
                                <button value={{ task.tid }} type="submit" name='check' onclick="document.getElementById('check').submit();"
                                    class="btn btn-red btn-sm" style="margin-top: -100px; margin-bottom: -100px"><i
                                    class="fa fa-check"></i></button>
                            </form>
                        </div>
                    {% else %}
                        <div class="col-sm-3">
                            <a disabled="disabled" class="btn btn-grey btn-sm" style="margin-top: -100px; margin-bottom: -100px"><i
                                class="fa fa-check"></i></a>
                        </div>
                    {% endif %}
                </div>
                <div class="row ml-0 mt-2">
                    {% if task.status == 3 %}
                        <div class="badge badge-success">DONE</div>
                    {% elif task.status == 2 %}
                        <div class="badge badge-default">IN PROGRESS</div>
                    {% elif task.status == 1 %}
                        <div class="badge badge-warning">CANCELLED</div>
                    {% elif task.status == 0 %}
                        <div class="badge badge-danger">EXPIRED</div>
                    {% endif %}
                    {% if task.priority == 4 %}
                        <div class="badge badge-danger ml-1">MAX PRIOR</div>
                    {% elif task.priority == 3 %}
                        <div class="badge badge-warning ml-1">HIGH PRIOR</div>
                    {% elif task.priority == 2 %}
                        <div class="badge badge-primary ml-1">MEDIUM PRIOR</div>
                    {% elif task.priority == 1 %}
                        <div class="badge badge-info ml-1">LOW PRIOR</div>
                    {% elif task.priority == 0 %}
                        <div class="badge badge-default ml-1">MIN PRIOR</div>
                    {% endif %}
                    {% if task.parent %}
                        <a style="width: 22%; margin-right: -1px" class="badge hoverable badge-pill blue trigger ml-1" href="{% url 'tc_web:show_task' task.parent %}">PARENT<i class="fa fa-arrow-up"></i></a>
                    {% endif %}
                    {% if task.childs %}

                            <a style="width: 13%" class="ml-1 trigger hoverable badge badge-pill blue dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-group"></i>
                            </a>
                            <ul class="dropdown-menu" style="overflow-y: scroll; overflow-x: hidden; max-height: 300px; width: 200px">
                                {% for child_task in task.childs %}
                                    {% include "tc_web/tasks/tree_view_template.html" with node=child_task %}
                                {% endfor %}
                            </ul>
                    {% endif %}
                </div>
                {% if project %}
                  <div class="row">
                        <div class="col-sm-6 mt-2">
                            <a href="{% url 'tc_web:profile' user_id=task.creator_uid %}" class="btn btn-sm btn-unique" style="margin-bottom: -10px; width: 110%">Maker:{{ project.admin_name|truncatechars:10 }}</a>
                        </div>
                        <div class="col-sm-6 mt-2">
                            <a href="{% url 'tc_web:profile' user_id=task.uid %}" class="btn btn-sm btn-unique" style=" margin-bottom: -10px; width: 100%">Exec:{{ task.receiver_name|truncatechars:9 }}</a>
                        </div>
                    </div>
                {% elif task.pid %}
                    <div class="row">
                        <div class="col-sm-6 mt-2">
                            <a href="{% url 'tc_web:project' project_id=task.pid %}" class="btn btn-sm btn-red" style="margin-bottom: -10px; width: 110%">Proj:{{ task.project_name|truncatechars:11 }}</a>
                        </div>
                        <div class="col-sm-6 mt-2">
                            <a href="{% url 'tc_web:profile' user_id=task.uid %}" class="btn btn-sm btn-unique" style=" margin-bottom: -10px; width: 100%">Exec:{{ task.receiver_name|truncatechars:9 }}</a>
                        </div>
                    </div>
                {% else %}
                <div class="row">
                    <div class="col-sm-12 mt-2">
                        <a class="btn btn-sm btn-red" href="{% url 'tc_web:profile' user_id=user.id  %}" style="width: 95%; margin-bottom: -10px">Personal task</a>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Card footer -->
            <div class="rounded-bottom mdb-color darken-1 text-center pt-3">
                <ul class="list-unstyled list-inline font-small">
                    <li class="list-inline-item pr-2">
                        {% if task.deadline %}
                        <a class="white-text"><i class="fa fa-clock-o pr-1"></i>{{task.deadline|date:"d M, H:i"}}</a>
                        {% else %}
                        <a class="white-text"><i class="fa fa-clock-o pr-1"></i>No deadline</a>
                        {% endif %}
                    </li>
                    <li class="list-inline-item pr-2"><a href="{% url 'tc_web:show_task' task_id=task.tid  %}" class="white-text"><i class="fa fa-arrow-right pr-1"></i>show</a></li>
                    {% if task.has_rights %}
                        <li class="list-inline-item pr-2"><a href="{% url 'tc_web:change_task' task_id=task.tid  %}" class="white-text"><i class="fa fa-edit pr-1"></i>edit</a></li>
                    {% endif %}
                    {% if task.pid %}
                        {% if task.has_rights %}
                        <li class="list-inline-item pr-2"><a href="{% url 'tc_web:add_child_project_task' project_id=task.pid task_id=task.tid  %}" class="white-text"><i class="fa fa-plus pr-1"></i>child</a></li>
                        {% endif %}
                    {% else %}
                        {% if task.has_rights %}
                            <li class="list-inline-item pr-2"><a href="{% url 'tc_web:add_child_task' task_id=task.tid  %}" class="white-text"><i class="fa fa-plus pr-1"></i>child</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
        <!--/.Card-->

    </div>

tc_site/web_application/tc_web/templates/tc_web/tasks/tasks.html
{% extends 'base.html' %}
{% block head %}
    <!--
    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    -->
{% endblock %}
{% block content %}
{% if tasks_list %}
<div class="row">
    {% for task in tasks_list %}
        {% include 'tc_web/tasks/task_card.html' with task=task %}
    {% endfor %}
</div>
{% else %}
<div class="card">
    <!--Card content-->
    <div class="card-body">
        <h4 class="card-title text-center">No tasks available</h4>
    </div>
</div>
{% endif %}
<!--Grid column-->
{% endblock %}

{% block add_buttons %}
<div class="fixed-action-btn" style="bottom: 45px; right: 24px; z-index: 1000">
    <a class="btn-floating btn-lg red" href="{% url 'tc_web:add_task' %}">
        <i class="fa fa-plus"></i>
    </a>
</div>
{% endblock %}

{% block links %}
<ul class="navbar-nav mr-auto">
    {% if user.is_authenticated %}
    <li class="nav-item active">
        <a class="nav-link"
           href="{% url 'tc_web:tasks' %}">Tasks</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'tc_web:projects' %}">Projects</a>
    </li>
    {% endif %}

</ul>
{% endblock %}

{% block errors %}
    {% include 'tc_web/error.html' with errors=errors %}
{% endblock %}

{% block navbar %}
    {% include 'tc_web/tasks/query_bar.html' %}
{% endblock %}

{% block scripts %}
    <script>
    function clicked(e) {
        if (!confirm('are you sure?'))
            return false;
        return true;
    }
    </script>
{% endblock %}

tc_site/web_application/tc_web/templates/tc_web/tasks/tree_view_template.html
{% if node.childs %}
    <li>
        <div class="row">
            <div class="col-sm-1">
            {% if node.status == 3 %}
                <i class="ml-1 mt-1 fa fa-check"></i>
            {% else %}
                <i class="ml-1 mt-1 fa fa-close"></i>
           {% endif %}
            </div>
            <div class="col-sm-9">
                <a style="margin-left: -30px" class="dropdown-item" href="{% url 'tc_web:show_task' node.tid %}">{{ node.title|truncatechars:20 }}   <i class="fa fa-arrow-down"></i></a>
            </div>
        </div>
    </li>
    <div class="dropdown-divider"></div>
    {% for child in node.childs %}
        {% include 'tc_web/tasks/tree_view_template.html' with node=child %}
    {% endfor %}
    <div class="dropdown-divider"></div>
{% else %}
    <li>
        <div class="row">
            <div class="col-sm-1">
            {% if node.status == 3 %}
                <i class="ml-1 mt-1 fa fa-check"></i>
            {% else %}
                <i class="ml-1 mt-1 fa fa-close"></i>
           {% endif %}
            </div>
            <div class="col-sm-9">
                <a style="margin-left: -30px" class="dropdown-item" href="{% url 'tc_web:show_task' node.tid %}">{{ node.title|truncatechars:20 }}</a>
            </div>
        </div>
    </li>
{% endif %}