tc_site/web_application/main_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from main_system import (
    views,
    startup,
    decorators,
)
from . import settings
import django.views.static

handler404 = 'tc_web.views.err404'
handler500 = 'tc_web.views.err500'

urlpatterns = [
    url(r'^accounts/login/$',
        decorators.startup_page_init('search')(auth_views.login),
        name='login'),
    url(r'^accounts/logout/$',
        auth_views.logout,
        {'next_page': '/'},
        name='logout'),
    url(r'^accounts/signup/$', views.signup, name='signup'),

    path('tc_web/', include('tc_web.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
]

if not settings.DEBUG:
    urlpatterns.append(path('static/<path>.', django.views.static.serve,
                            {'document_root': settings.STATIC_ROOT}))


startup.start_up()

tc_site/web_application/tc_web/urls.py
from django.urls import path
from django.conf.urls import url
from tc_web import views
from tc_web.tasks import views as task_views
from tc_web.projects import views as project_views


app_name = 'tc_web'


urlpatterns = [
    path('', views.index, name='index'),

    path('tasks/', task_views.tasks, name='tasks'),
    path('projects/', project_views.projects, name='projects'),

    path('tasks/add_task/', task_views.add_task, name='add_task'),
    path('tasks/<int:project_id>/add_task/',
         task_views.add_task,
         name='add_project_task'),
    path('tasks/<int:project_id>/add_task/<int:task_id>/',
         task_views.add_task,
         name='add_child_project_task'),
    path('tasks/add_task/<int:task_id>/',
         task_views.add_task,
         name='add_child_task'),
    path('tasks/change_task/<int:task_id>/',
         task_views.change_task,
         name='change_task'),
    path('tasks/show_task/<int:task_id>/',
         task_views.show_task,
         name='show_task'),

    path('projects/add_project/',
         project_views.add_project,
         name='add_project'),

    path('project/<int:project_id>/', task_views.project, name='project'),
    path('project/<int:project_id>/add_user',
         project_views.add_user,
         name='add_user'),
    path('projects/change_project/<int:project_id>/',
         project_views.change_project,
         name='change_project'),

    path('profile/id<int:user_id>/', views.profile, name='profile'),
    path('profile/change_profile/<int:user_id>/',
         views.change_profile,
         name='change_profile'),

    url(r'^api/get_users/', views.get_users, name='get_users'),
    path('api/get_project_users/<int:project_id>/',
         views.get_project_users,
         name='get_project_users')
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

tc_site/web_application/tc_web/models.py
from peewee import *

tc_site/web_application/tc_web/forms.py
from django import forms
from time_candle.enums.status import status_dict, Status
from time_candle.enums.priority import priority_dict, Priority


class ChangeProfileForm(forms.Form):
    nickname = forms.CharField(max_length=30,
                               required=True)
    about = forms.CharField(max_length=550, required=False)

tc_site/web_application/tc_web/projects/forms.py
from django import forms


class ProjectForm(forms.Form):
    title = forms.CharField(
        label='project\'s title', max_length=30, required=True)
    description = forms.CharField(label='description', required=False,
                                  widget=forms.Textarea)

tc_site/web_application/tc_web/tasks/forms.py
from django import forms
from time_candle.enums.status import status_dict, Status
from time_candle.enums.priority import priority_dict, Priority
from tempus_dominus.widgets import DateTimePicker


STATUS_CHOICES = tuple(status_dict.items())
PRIORITY_CHOICES = tuple(priority_dict.items())


class AddTask(forms.Form):
    title = forms.CharField(label='task\'s title', max_length=60, required=True)
    comment = forms.CharField(label='comment', max_length=155, required=False)
    deadline_time = forms.CharField(label='deadline', required=False,
                                    help_text='Format: YYYY-MM-DD hh:mm:ss',
                                    widget=DateTimePicker())
    priority = forms.ChoiceField(
        label='priority', choices=PRIORITY_CHOICES, initial=Priority.MEDIUM,
        required=False, widget=forms.Select())
    status = forms.ChoiceField(
        label='status', choices=STATUS_CHOICES, initial=Status.IN_PROGRESS,
        required=False)
    period = forms.FloatField(label='period in days', required=False)


class ChangeTask(forms.Form):
    comment = forms.CharField(label='comment', max_length=155, required=False)
    deadline_time = forms.CharField(label='deadline', required=False,
                                    help_text='Format: YYYY-MM-DD hh:mm:ss',
                                    widget=DateTimePicker())
    priority = forms.ChoiceField(label='priority', choices=PRIORITY_CHOICES,
                                 required=False, widget=forms.Select())
    status = forms.ChoiceField(
        label='status', choices=STATUS_CHOICES, required=False)

tc_site/web_application/tc_web/projects/views.py
from django.http import Http404
from django.shortcuts import (
    render,
    redirect,
)
from django.urls import reverse
from django.contrib.auth.models import User
from time_candle.exceptions import AppException
from tc_web.projects import (
    forms,
    shortcuts,
)
from main_system import decorators
from main_system import shortcuts as base_shortcuts
from tc_web import logger
from django.contrib.auth.decorators import login_required


@login_required
@decorators.startup_page_init('search')
def projects(request):
    controller = base_shortcuts.get_controller(request)
    projects_list = controller.get_projects('')

    context = {
        'projects_list': projects_list
    }

    try:
        redirect_view = shortcuts.project_card_post_form(request, controller)

        # if we can redirect, then do it, else just render or render with errors
        # our template
        if redirect_view:
            logger.debug('redirect due to changes...')
            return redirect_view

        # adding some fields for better view
        shortcuts.init_projects(request, controller, projects_list)

    except AppException as e:
        context['errors'] = e.errors.value
        logger.warning(e.errors.value)

        # the errors doesn't
        shortcuts.init_projects(request, controller, projects_list)

    logger.debug('all projects rendered')
    return render(request, 'tc_web/projects/projects.html', context)


@login_required
@decorators.startup_page_init('search')
def add_project(request):
    if request.method == 'POST':
        form = forms.ProjectForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')

            controller = base_shortcuts.get_controller(request)

            controller.add_project(title=title,
                                   description=description,
                                   members=[])
            logger.debug('project added')

            return redirect(reverse('tc_web:projects'))

    else:
        form = forms.ProjectForm()

    return render(request, 'tc_web/projects/add_project.html', {'form': form})


@login_required
@decorators.startup_page_init('search')
def change_project(request, project_id):
    context = {'errors': None}
    controller = base_shortcuts.get_controller(request)

    if request.method == 'POST':
        form = forms.ProjectForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')

            # if description if empty we pass it as not-to-change param
            if not description:
                description = None

            try:
                controller.change_project(project_id, title, description)
                logger.debug('project changed')

                return redirect(reverse('tc_web:projects'))
            except AppException as e:
                logger.debug(e.errors.value)
                context['errors'] = e.errors.value

    else:
        form = forms.ProjectForm()

    context['form'] = form

    # try because we can have some problems with rights when we try to visit
    # page
    try:
        project = controller.get_project(project_id)
        context['project'] = project
        form.fields['title'].widget.attrs.update({'value': project.title})
        form.fields['description'].widget.attrs.update(
            {'placeholder': project.description})

    except AppException as e:
        logger.warning(e.errors.value)
        raise Http404

    # if you are not admin and there was no errors for you before
    if request.user.id != project.admin_uid and not context['errors']:
        logger.debug('dont have rights for changing the project')
        context['errors'] = 'You know that you cannot do that, right?'

    return render(request, 'tc_web/projects/change_project.html', context)


@login_required
@decorators.startup_page_init('search')
def add_user(request, project_id):
    context = {}
    controller = base_shortcuts.get_controller(request)

    if request.method == 'POST':

        # trying to add user to project
        try:
            # searching selected user in database
            try:
                if 'search_user' in request.POST \
                        and request.POST['search_user']:
                    user_id = User.objects.get(
                        username=request.POST['search_user']).id
                else:
                    user_id = None

            except User.DoesNotExist:
                # we need this for more elegant way to catch exception
                errors = type('dummy', (), {})()
                errors.value = 'User does not exists'
                logger.warning(errors.value)
                raise AppException(errors)

            controller.add_user_to_project(user_id, project_id)
            logger.debug('user to project was added')

            return redirect(reverse('tc_web:project', args=(project_id,)))

        except AppException as e:
            context['errors'] = e.errors.value

    # try because we can have some problems with rights when we try to visit
    # page
    try:
        project = controller.get_project(project_id)

    except AppException as e:
        logger.warning(e.errors.value)
        raise Http404

    # if you are not admin and there was no errors for you before
    if request.user.id != project.admin_uid and not context['errors']:
        context['errors'] = 'You know that you cannot do that, right?'

    return render(request, 'tc_web/projects/add_user.html', context)

tc_site/web_application/tc_web/views.py
from django.http import (
    HttpResponse,
    Http404,
)
from django.shortcuts import render, redirect
from django.urls import reverse
from time_candle.exceptions import AppException
from tc_web import (
    forms,
    logger,
)
from main_system import (
    shortcuts,
    decorators,
)
from django.contrib.auth.models import User
import json
from django.contrib.auth.decorators import login_required


def err404(request, exception):
    logger.debug('Http404 error raised')
    return render(
        request, 'tc_web/404.html', status=404)


def err500(request, exception):
    logger.debug('Http500 error raised')
    return render(
        request, 'tc_web/500.html', status=500)


@decorators.startup_page_init('search')
def index(request):
    return render(request, 'tc_web/index.html')


@decorators.startup_page_init('search')
def profile(request, user_id):
    controller = shortcuts.get_controller(request)
    context = {}

    try:
        django_user = User.objects.get(id=user_id)
        lib_user = controller.get_user(user_id)
    except (User.DoesNotExist, AppException):
        raise Http404

    # merge two user objects to get one full user info
    screen_user = shortcuts.merge_instances(django_user, lib_user)
    context['screen_user'] = screen_user

    if user_id == request.user.id:
        logger.debug('rendering delete button')

        if request.method == 'POST':
            logger.debug(request.POST)
            if 'delete' in request.POST:
                controller.remove_message(request.POST['delete'])
                return redirect(request.META.get('HTTP_REFERER'))

        logger.debug('getting our messages')
        messages = controller.get_messages()
        context['messages'] = messages

    return render(request, 'tc_web/profile.html', context)


# function for autocomplete user search
def get_users(request):
    logger.debug('ajax request to get all users has been sent')

    if request.is_ajax():
        q = request.GET.get('term', '')
        re = '^' + q + '+'
        users = User.objects.filter(username__regex=re)
        results = []
        for user in users:
            user_json = {}
            user_json['id'] = user.id
            user_json['label'] = user.username
            user_json['value'] = user.username
            results.append(user_json)
        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    logger.debug('ajax request was accepted')
    return HttpResponse(data, mimetype)


# function for autocomplete project user search
def get_project_users(request, project_id):
    logger.debug('ajax request to get project users has been sent')
    controller = shortcuts.get_controller(request)
    logger.debug('users were taken from controller')

    if request.is_ajax():
        q = request.GET.get('term', '')
        users = controller.get_users(project_id)
        users = [user for user in users if user.login.startswith(q)]
        results = []
        for user in users:
            user_json = {}
            user_json['id'] = user.uid
            user_json['label'] = user.login
            user_json['value'] = user.login
            results.append(user_json)
        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    logger.debug('ajax request was accepted')
    return HttpResponse(data, mimetype)


@login_required
@decorators.startup_page_init('search')
def change_profile(request, user_id):
    context = {}
    controller = shortcuts.get_controller(request)

    if request.method == 'POST':
        form = forms.ChangeProfileForm(request.POST)
        if form.is_valid():
            about = form.cleaned_data.get('about')
            nickname = form.cleaned_data.get('nickname')
            try:
                controller.change_user(user_id, nickname, about)
                logger.debug('user was changed')
                return redirect(reverse('tc_web:profile', args=(user_id,)))

            except AppException as e:
                context['errors'] = e.errors.value

    else:
        form = forms.ChangeProfileForm()
        user = controller.get_user(user_id)

        # init fields with default values
        form.fields['nickname'].widget.attrs.update({'value': user.nickname})
        form.fields['about'].widget.attrs.update({'value': user.about})

    context['form'] = form

    return render(request, 'tc_web/change_profile.html', context)

tc_site/web_application/tc_web/templates/tc_web/projects/add_project.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-md-center">
    <div class="col-md-8 col-lg-6 col-sm-12">
        <div class="card">
            <div class="card-body">
                <p class="h4 text-center">Add project</p>
                <br>
                <form method="post" class="text-center">
                    {% csrf_token %}
                    {% for field in form %}
                    <label class="grey-text h5">
                        {{ field.label_tag }}</label>
                    <br>
                    <div class="container bm-2">
                        {{ field }}
                    </div>
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    <br>
                    {% endfor %}

                    <hr>
                    <div class="row justify-content-sm-center mt-2">
                        <div class="col-sm-5">
                            <a class="btn btn-unique" onClick="javascript:history.go(-1);">Back</a>
                        </div>
                        <div class="col-sm-5">
                            <button type="submit" class="btn btn-unique">Add</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block errors %}
    {% include 'tc_web/error.html' with errors=errors %}
{% endblock %}

tc_site/web_application/tc_web/templates/tc_web/projects/add_user.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-md-center">
    <div class="col-lg-4 col-md-8 col-sm-12">
        <div class="card">
            <div class="card-body">
                <p class="h4 text-center">Add user</p>
                <form method="post" class="text-center">
                    {% csrf_token %}
                    <div class="fieldWrapper" style="z-index: 10000">
                        <input id="search_user" name="search_user" style="z-index: 10000" type="text"

                               placeholder="Username" aria-label="Search">
                    </div>

                    <hr>
                    <div class="row justify-content-sm-center mt-2">
                        <div class="col-sm-5">
                            <a class="btn btn-unique" onClick="javascript:history.go(-1);">Back</a>
                        </div>
                        <div class="col-sm-5">
                            <button type="submit" class="btn btn-unique">Add</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block errors %}
    {% include 'tc_web/error.html' with errors=errors %}
{% endblock %}

{% block scripts %}
<script>
$(function() {
    $("#search_user").autocomplete({
        source: "/tc_web/api/get_users",
        minLength: 2,
        autoFocus: true,
    });
});

</script>
{% endblock %}

tc_site/web_application/tc_web/templates/tc_web/projects/change_project.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-md-center">
    <div class="col-md-8 col-lg-6 col-sm-12">
        <div class="card">
            <div class="card-body">
                <p class="h4 text-center mb-4">Change project: {{ project.title }}<span class="grey-text">@{{ task.tid }}</span></p>

                <form method="post" class="text-center">
                    {% csrf_token %}
                    {% for field in form %}
                    <label class="grey-text h5">
                        {{ field.label_tag }}</label>
                    <br>
                    <div class="container bm-2">
                        {{ field }}
                    </div>
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    <br>
                    {% endfor %}
                    <hr>
                    <div class="row justify-content-sm-center mt-2">
                        <div class="col-sm-5">
                            <a class="btn btn-unique" style="width: 70%" onClick="javascript:history.go(-1);">Back</a>
                        </div>
                        <div class="col-sm-5">
                            <button type="submit" class="btn btn-unique">Commit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block errors %}
    {% include 'tc_web/error.html' with errors=errors %}
{% endblock %}

tc_site/web_application/tc_web/templates/tc_web/projects/project_card.html
<!--Grid column-->
<div class="col-lg-4 col-md-6 col-sm-12 mb-4">

    <!--Card-->
    <div class="card">
        <!--Card content-->
        <div class="card-body">
            <!--Title-->
            <div class="row" style="margin-bottom: -20px">
                <div class="col-sm-9">
                    <h4 class="card-title">{{ project.title|truncatechars:18 }}</h4>
                </div>
                <div class="col-sm-3">
                    {% if project.has_rights %}
                    <form id="del" method="post">
                        {% csrf_token %}
                        <button value={{ project.pid }} type="submit" name='delete' onclick="return confirm('Are you sure?')"
                            class="btn btn-red btn-sm" style="margin-top: -3px"><i
                            class="fa fa-times"></i></button>

                    </form>
                    {% else %}
                        <a disabled="disabled" class="btn btn-grey btn-sm" style="margin-top: -3px"><i
                            class="fa fa-times"></i></a>
                    {% endif %}
                </div>
            </div>
            <hr>
            <!--Text-->
            <div class="row">
                <div class="col-sm-12">
                    <p class="card-text">{{ project.description|default:"No description provided"|truncatechars:45 }}</p>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-sm-6">
                    <a href="{% url 'tc_web:project' project.pid %}" class="btn btn-sm btn-red" style="margin-bottom: -10px; width: 110%">Check tasks</a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'tc_web:profile' project.admin_uid %}" class="btn btn-sm btn-unique" style=" margin-bottom: -10px; width: 100%">Admin:{{ project.admin_name|truncatechars:9 }}</a>
                </div>
            </div>
            <!--TODO: REAL url-->
        </div>
    <!-- Card footer -->
        <div class="rounded-bottom mdb-color darken-1 text-center pt-3">
            <ul class="list-unstyled list-inline font-small">
                {% if project.admin_uid == user.id %}
                <li class="list-inline-item pr-2"><a href="{% url 'tc_web:change_project' project.pid %}" class="white-text"><i class="fa fa-arrow-right pr-1"></i>change</a></li>
                {% else %}
                    <li class="list-inline-item pr-2"><a class="white-text"> </a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!--/.Card-->
</div>

tc_site/web_application/tc_web/templates/tc_web/projects/projects.html
{% extends 'base.html' %}
{% block content %}
{% if projects_list %}
<div class="row">
{% for project in projects_list %}
    {% include 'tc_web/projects/project_card.html' with project=project %}
{% endfor %}
</div>
{% else %}
 <div class="card">

     <!--Card content-->
     <div class="card-body">
         <h4 class="card-title text-center">No projects available</h4>
     </div>
 </div>
{% endif %}
<!--Grid column-->
{% endblock %}

{% block add_buttons %}
<div class="fixed-action-btn" style="bottom: 45px; right: 24px; z-index: 1000">
    <a class="btn-floating btn-lg red" href="{% url 'tc_web:add_project' %}">
        <i class="fa fa-plus"></i>
    </a>
</div>
{% endblock %}

{% block links %}
<ul class="navbar-nav mr-auto">
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'tc_web:tasks' %}">Tasks</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'tc_web:projects' %}">Projects</a>
    </li>
    {% endif %}

</ul>
{% endblock %}

{% block errors %}
    {% include 'tc_web/error.html' with errors=errors %}
{% endblock %}